2024-08-07 13:02:50 | INFO     | server:search:34 - 用户输入的文本：测试查询
2024-08-07 13:02:50 | ERROR    | server:search:40 - 发生异常：模拟服务器错误
Traceback (most recent call last):

  File "D:\anaconda\envs\faq_chatbot\lib\threading.py", line 973, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x0000019BAA5A30A0>
    └ <WorkerThread(AnyIO worker thread, started 39736)>

  File "D:\anaconda\envs\faq_chatbot\lib\threading.py", line 1016, in _bootstrap_inner
    self.run()
    │    └ <function WorkerThread.run at 0x0000019BCF06AB90>
    └ <WorkerThread(AnyIO worker thread, started 39736)>

  File "D:\anaconda\envs\faq_chatbot\lib\site-packages\anyio\_backends\_asyncio.py", line 859, in run
    result = context.run(func, *args)
             │       │   │      └ ()
             │       │   └ functools.partial(<function search at 0x0000019BCF01B250>, query_data=QueryData(text='测试查询'))
             │       └ <method 'run' of '_contextvars.Context' objects>
             └ <_contextvars.Context object at 0x0000019BCF074600>

> File "D:\Projects\FAQ_Chatbot\server.py", line 36, in search
    query_vec = get_embedding(query_data.text)
                │             │          └ '测试查询'
                │             └ QueryData(text='测试查询')
                └ <function test_search_endpoint_server_error.<locals>.mock_get_embedding at 0x0000019BAC8F8940>

  File "D:\Projects\FAQ_Chatbot\unit_test\test_server.py", line 34, in mock_get_embedding
    raise Exception("模拟服务器错误")

Exception: 模拟服务器错误
2024-08-07 13:05:25 | INFO     | config.log_config:test_logging:50 - 这是一条信息。
2024-08-07 13:05:25 | WARNING  | config.log_config:test_logging:51 - 这是一条警告。
2024-08-07 13:05:25 | ERROR    | config.log_config:test_logging:52 - 这是一条错误信息。
2024-08-07 13:05:25 | CRITICAL | config.log_config:test_logging:53 - 这是一条严重错误信息。
2024-08-07 13:05:25 | INFO     | server:search:34 - 用户输入的文本：测试查询
2024-08-07 13:05:25 | INFO     | server:search:34 - 用户输入的文本：测试查询
2024-08-07 13:05:25 | ERROR    | server:search:40 - 发生异常：模拟服务器错误
Traceback (most recent call last):

  File "D:\anaconda\envs\faq_chatbot\lib\threading.py", line 973, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x000002791EE530A0>
    └ <WorkerThread(AnyIO worker thread, started 35232)>

  File "D:\anaconda\envs\faq_chatbot\lib\threading.py", line 1016, in _bootstrap_inner
    self.run()
    │    └ <function WorkerThread.run at 0x00000279439A6B90>
    └ <WorkerThread(AnyIO worker thread, started 35232)>

  File "D:\anaconda\envs\faq_chatbot\lib\site-packages\anyio\_backends\_asyncio.py", line 859, in run
    result = context.run(func, *args)
             │       │   │      └ ()
             │       │   └ functools.partial(<function search at 0x00000279439531C0>, query_data=QueryData(text='测试查询'))
             │       └ <method 'run' of '_contextvars.Context' objects>
             └ <_contextvars.Context object at 0x00000279434E2440>

> File "D:\Projects\FAQ_Chatbot\server.py", line 36, in search
    query_vec = get_embedding(query_data.text)
                │             │          └ '测试查询'
                │             └ QueryData(text='测试查询')
                └ <function test_search_endpoint_server_error.<locals>.mock_get_embedding at 0x00000279439CEA70>

  File "D:\Projects\FAQ_Chatbot\unit_test\test_server.py", line 34, in mock_get_embedding
    raise Exception("模拟服务器错误")

Exception: 模拟服务器错误
2024-08-07 13:10:19 | INFO     | test_log_config:test_log_to_file:30 - This is a test log message
2024-08-07 13:11:06 | INFO     | test_log_config:test_log_to_file:30 - This is a test log message
2024-08-07 13:12:01 | INFO     | test_log_config:test_log_to_file:31 - This is a test log message
2024-08-07 13:12:45 | INFO     | test_log_config:test_log_to_file:31 - This is a test log message
2024-08-07 13:13:07 | INFO     | test_log_config:test_log_to_file:31 - This is a test log message
2024-08-07 13:13:33 | INFO     | test_log_config:test_log_to_file:29 - This is a test log message
2024-08-07 13:13:42 | INFO     | test_log_config:test_log_to_file:29 - This is a test log message
